export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_RESPONSE = "SIGN_IN_RESPONSE";
export const SIGNING_UP = "SIGNING_UP";
export const SIGN_UP_RESPONSE = "SIGN_UP_RESPONSE";
export const SIGN_IN_SUCCESSFULLY = "SIGN_IN_SUCCESSFULLY";

export const IS_GETTING_PROFILE = "IS_GETTING_PROFILE";
export const GET_PROFILE_SUCCESSFULLY = "GET_PROFILE_SUCCESSFULLY";

export const GET_SPECIALIZES_OK = "GET_SPECIALIZES_OK";

export const IS_GETTING_USERS = "IS_GETTING_USERS";
export const GET_USERS_SUCCESSFULLY = "GET_USERS_SUCCESSFULLY";

export const IS_GETTING_TAGS = "IS_GETTING_TAGS";
export const GET_TAGS_SUCCESSFULLY = "GET_TAGS_SUCCESSFULLY";
export const IS_DELETING_TAGS = "IS_DELETING_TAGS";
export const DELETE_TAGS_SUCCESSFULLY = "DELETE_TAGS_SUCCESSFULLY";
export const IS_UPDATING_TAGS = "IS_UPDATING_TAGS";
export const UPDATE_TAGS_SUCCESSFULLY = "UPDATE_TAGS_SUCCESSFULLY";
export const UPDATE_TAGS_FAILED = "UPDATE_TAGS_FAILED";

export const IS_GETTING_TEACHERS = "IS_GETTING_TEACHERS";
export const GET_TEACHERS_OK = "GET_TEACHERS_OK";

export const UPDATING_DESCTIPTION = "UPDATING_DESCTIPTION";
export const UPDATE_DESCTIPTION_RESPONSE = "UPDATE_DESCTIPTION_RESPONSE";
export const UPDATING_BASIC_INFO = "UPDATING_BASIC_INFO";
export const UPDATE_BASIC_INFO_RESPONSE = "UPDATE_BASIC_INFO_RESPONSE";

// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
// export const SIGNING_IN = 'SIGNING_IN'
