export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_RESPONSE = "SIGN_IN_RESPONSE";
export const SIGNING_UP = "SIGNING_UP";
export const SIGN_UP_RESPONSE = "SIGN_UP_RESPONSE";
export const SIGN_IN_SUCCESSFULLY = "SIGN_IN_SUCCESSFULLY";

export const IS_GETTING_PROFILE = "IS_GETTING_PROFILE";
export const GET_PROFILE_SUCCESSFULLY = "GET_PROFILE_SUCCESSFULLY";
export const IS_GETTING_USER = "IS_GETTING_USER";
export const GET_USER_SUCCESSFULLY = "GET_USER_SUCCESSFULLY";
export const GET_CURRENT_CONTRACT_SUCCESSFULLY =
  "GET_CURRENT_CONTRACT_SUCCESSFULLY";
export const IS_GETTING_CURRENT_CONTRACT = "IS_GETTING_CURRENT_CONTRACT";

export const GET_SPECIALIZES_OK = "GET_SPECIALIZES_OK";
export const GET_TAGS_OK = "GET_TAGS_OK";

export const IS_GETTING_USERS = "IS_GETTING_USERS";
export const GET_USERS_SUCCESSFULLY = "GET_USERS_SUCCESSFULLY";

export const IS_ADDING_TAG = "IS_ADDING_TAG";
export const ADD_TAG_SUCCESSFULLY = "ADD_TAG_SUCCESSFULLY";
export const IS_DELETING_TAG = "IS_DELETING_TAG";
export const DELETE_TAG_SUCCESSFULLY = "DELETE_TAG_SUCCESSFULLY";
export const IS_UPDATING_TAG = "IS_UPDATING_TAG";
export const UPDATE_TAG_SUCCESSFULLY = "UPDATE_TAG_SUCCESSFULLY";
export const UPDATE_TAG_FAILED = "UPDATE_TAG_FAILED";

export const IS_GETTING_TEACHERS = "IS_GETTING_TEACHERS";
export const GET_TEACHERS_OK = "GET_TEACHERS_OK";

export const UPDATING_PASSWORD = "UPDATING_PASSWORD";
export const UPDATE_PASSWORD_RESPONSE = "UPDATE_PASSWORD_RESPONSE";
export const UPDATING_TAGS = "UPDATING_TAGS";
export const UPDATE_TAGS_RESPONSE = "UPDATE_TAGS_RESPONSE";
export const UPDATING_DESCTIPTION = "UPDATING_DESCTIPTION";
export const UPDATE_DESCTIPTION_RESPONSE = "UPDATE_DESCTIPTION_RESPONSE";
export const UPDATING_BASIC_INFO = "UPDATING_BASIC_INFO";
export const UPDATE_BASIC_INFO_RESPONSE = "UPDATE_BASIC_INFO_RESPONSE";
export const UPDATING_AVATAR = "UPDATING_AVATAR";
export const UPDATE_AVATAR_RESPONSE = "UPDATE_AVATAR_RESPONSE";

export const IS_CREATING_CONTRACT = "IS_CREATING_CONTRACT";
export const CREATE_CONTRACT_OK = "CREATE_CONTRACT_OK";

export const GET_CONTRACTS_OK = "GET_CONTRACTS_OK";
export const IS_GETTING_CONTRACTS = "IS_GETTING_CONTRACTS";
export const GET_ADMINS_OK = "GET_ADMINS_OK";
export const IS_GETTING_ADMINS = "IS_GETTING_ADMINS";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";

export const GET_MY_CONTRACTS_OK = "GET_MY_CONTRACTS_OK";
export const IS_GETTING_MY_CONTRACT = "IS_GETTING_MY_CONTRACT";

export const RESET = "RESET";

export const ENDING_CONTRACT = "ENDING_CONTRACT";
export const END_CONTRACT_OK = "END_CONTRACT_OK";
export const REJECTING_CONTRACT = "REJECTING_CONTRACT";
export const REJECT_CONTRACT_OK = "REJECT_CONTRACT_OK";
export const PAYING_CONTRACT = "PAYING_CONTRACT";
export const PAY_CONTRACT_OK = "PAY_CONTRACT_OK";
export const ACCEPTING_CONTRACT = "ACCEPTING_CONTRACT";
export const ACCEPT_CONTRACT_OK = "ACCEPT_CONTRACT_OK";
export const RATING_CONTRACT = "RATING_CONTRACT";
export const RATE_CONTRACT_OK = "RATE_CONTRACT_OK";

export const UPDATING_USER_STATUS = "UPDATING_USER_STATUS";
export const UPDATE_USER_STATUS_OK = "UPDATE_USER_STATUS_OK";
